# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BuDeJie' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.10'
  pod 'SDWebImage', '~> 3.7.6'
  pod 'SVProgressHUD', '~> 2.0.3'

  target 'BuDeJieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuDeJieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
